[tool.poetry]
name = "pythonexamples"
version = "0.1.0"
description = ""
authors = ["Karlito16 <karlo.dimjasevic@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
